NAME = MatroxMGA2164W_reloc

PROJECTVERSION = 1.1
LANGUAGE = English

CLASSES = MatroxMGA2164W.m MGAModes.m

HFILES = MatroxMGA2164W.h MGAVga.h

CFILES = MGAVga.c

OTHERSRCS = Makefile Makefile.preamble Makefile.postamble\
            Makefile.driver_preamble Load_Commands.sect

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make
SOURCEMODE = 444

LIBS = 
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
